# https://docs.travis-ci.com/user/reference/xenial/#python-support
# It says Xenial has Python 2.7, 3.6, and 3.7 (?)
# We're not using language: python because that creates a virtualenv, which is
# specific to a Python version.  MyPy needs both in the same environment.

dist: xenial
cache: pip

addons:
    apt:
        packages:
            # build/dev.sh ubuntu-deps
            - python-dev
            - gawk
            - time
            - libreadline-dev
            # test/spec.sh install-shells
            - busybox-static
            - mksh
            - zsh
              # since we're not using language: python
            - python3-setuptools
            - python-pip
            - python3-pip

before_install:
    - test/spec.sh link-busybox-ash

install:
    - pip install --user flake8 typing
    # mypy requires Python 3
    - pip3 install --user mypy
    # hack for cmark
    - build/dev.sh minimal

script:
    - test/lint.sh travis
    # Type checking with MyPy.  Problem: mypy requires Python 3, but Oil
    # requires Python 2.  The Travis environment doesn't like that.
    - types/run.sh travis
    - types/osh-parse.sh travis
    # Unit tests
    - test/unit.sh all-for-minimal
    # Spec tests
    - test/spec.sh smoke
    # Make sure dev build of yajl works
    - test/spec.sh oil-json
    - test/spec.sh interactive
    # TODO: get other spec tests running on Travis.
    # - test/spec.sh all

notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
